name: Check Production Website

on:
  workflow_dispatch:

jobs:
  check-production:
    runs-on: ubuntu-latest
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3
        with: 
          url: http://denverdemocrats.org|https://denverdemocrats.org
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
